name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL}}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL}}
  GITHUB_CLIENT_ID: foo
  GITHUB_CLIENT_SECRET: bar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run type-check
      - run: npm run lint
      - run: npm test -- --ci --maxWorkers=2 --colors
